### ISSUE TITLE
Missing partmodule ?

### ISSUE THREAD

**Issue by brustmopf** [linuxgurugamer/AGExt#5]
I may be wrong but I think there is an issue in the code.
When I check the log of KSP I find the following lines for almost every part being loaded (here a part from the remote tech mod

[LOG 21:17:02.464] RemoteTech: ModuleRTAntenna: OnDestroy
[LOG 21:17:02.464] RemoteTech: ModuleSPUPassive: OnDestroy
[LOG 21:17:02.467] PartLoader: Compiling Part 'REPOSoftTech/AmpYear/Parts/ampYear_Z100_ReserveBatteryPack/part/reserveBatteryPack'
[ERR 21:17:02.476] Cannot find a PartModule of typename 'ModuleAGX'

After trying to find the issue myself, I arrived at the following conclusion:
x the Partmodule code is commented out in the PartModule.cs file
x therefore the code doesn't actually declare a partmodule anywhere corresponding to ModuleAGX

Does it make sense ? Did I miss something ?

**Comment by linuxgurugamer** [comment]
you are correct in your conclusions, but the real issue is that the part module is being added to the parts.  That partmodule is depreciated, so you can ignore the error, but i'll make an note to remove the MM scripts which are adding it to the parts

**Comment by linuxgurugamer** [comment]
Try this test build:

https://jenkins.spacetux.net/job/A-F/job/AGExt/lastSuccessfulBuild/artifact/AGExt-2.3.3.3.zip

**Comment by brustmopf** [comment]
solved...

Thanks !

All that's left for me is to understand why the partmodule is deprecated, but i'll work that out...

BTW : thank you so much for all the work you're putting into maintaining these mods...

**Comment by linuxgurugamer** [comment]
My mistake, the partmodule is there, just in a different file.  The ModuleAGX is in the CommonMethods.cs file, I'm reverting the change.
This will teach me to not test before releasing.
Please download the latest, run your test and then, if it still happens, post a link to the entire log file

**Comment by brustmopf** [comment]
Hi guru,

sorry formy long silence. I hada bunch of stuff to deal with IRL.

anyway, i tested version 2.3.3.6 and I still have the same issue.
I am testing against KSP 1.4.3 win 64, but I don't think that should make a difference.
I have no mod apart from 
x action group
x ksp avc
x toolbar

here's link to my log file: https://pastebin.com/XTyFfrPr

**Comment by brustmopf** [comment]
Hi guru,

seems to work ( i deleted a previous comment where after testing and still seing the error I saw I had a version issue)

looks like it s working nicely

Thank you for your work and all the effort you put in keeping these mods alive and in good health...

need help ?
